# .github/labeler.yml

# Label for documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'README.md'

# Label for Docker changes
docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'Dockerfile'
      - 'docker-compose.yml'

# Label for release-related changes
release:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**'
      - 'pyproject.toml'
  - base-branch: 'main'
