# .github/labeler.yml

# Label for documentation changes
documentation:
  - changed-files:
    - 'docs/**'
    - 'README.md'

# Label for Docker changes
docker:
  - 'Dockerfile'
  - 'docker-compose.yml'

# Label for release-related changes
release:
  - 'src/**'
  - 'pyproject.toml'
