# .github/labeler.yml

# Label for documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      

# Label for Docker changes
docker:
  - changed-files:
    - any-glob-to-any-file:
      - '*docker*'
      - 'Docker*'

# Label for release-related changes
release:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**'
      - 'pyproject.toml'
      - 'LICENCE'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      
workflows:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/*'
        - '.github/labeler.yml'

github: 
  - changed-files:
      - any-glob-to-any-file:
        - '.gitignore'