# .github/labeler.yml

# Label for documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'README.md'
      

# Label for Docker changes
docker:
  - changed-files:
    - any-glob-to-any-file:
      - '*docker*'
      - 'Docker*'

# Label for release-related changes
release:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'src/**'
        - 'pyproject.toml'
        - 'LICENCE'
    - base-branch: 'main'

workflows:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/*'
        - '.github/labeler.yml'

github: 
  - changed-files:
      - any-glob-to-any-file:
        - '.gitignore'