name: Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs: 
      all-labels: ${{ steps.label-the-PR.outputs.all-labels }}
    steps:
      - name: Apply Labels
        id: label-the-PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
  
  check-changelog:
    needs: label
    if: |
      contains(needs.label.outputs.all-labels, 'release') ||
      contains(needs.label.outputs.all-labels, 'docker')
    uses: ./.github/workflows/check-changelog.yaml
    # with:
    #   pr_title: ${{ github.event.pull_request.title }}
    #   pr_number: ${{ github.event.pull_request.number }}
    #   pr_url: ${{ github.event.pull_request.html_url }}
    #   update_changelog: true
