name: Test Docker Workflow

on:
  workflow_run:
    workflows: [Semantic Versioning for Tags]
    types:
      - completed

  pull_request_target:
    branches:
      - develop
    types:
      - closed

  workflow_dispatch:
    
jobs:
  Build-and-publish-to-Dockerhub:
    if: |
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion  == 'success') ||
        (github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged &&
        contains(github.event.pull_request.labels.*.name, 'docker'))
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
                fetch-depth: '0'
        
        - name: Set up Python and install Dunamai
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'  # You can specify a specific version if needed

        - name: Install Dunamai
          run: |
            python -m pip install --upgrade pip
            pip install dunamai
        
        - name: Use Dunamai
          run: |
            # Example command using dunamai
            distance=$(dunamai from git --format "{distance}")
            branch=$(dunamai from git --format "{branch}")
            # Main logic
            if [ "$distance" = "0" ]; then
                dunamai from git --format "v{base}"
            elif [ "$branch" = "develop" ]; then
                dunamai from git --format "v{base}.dev{distance}"
            else
                dunamai from git --format "v{base}.dev{distance}+{commit}"
            fi
