name: Test Docker Workflow

on:
    pull_request_target:
        branches:
            - main
        types:
            - closed
    
    push:
        tags:
            - 'v*.*.*'
            
    workflow_dispatch:

jobs:
    Debug-PR-Event:
        runs-on: ubuntu-latest
        steps:
            - name: Print GitHub context
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Pull Request Merged: ${{ github.event.pull_request.merged }}"
                echo "Pull Request Labels: ${{ contains(github.event.pull_request.labels.*.name, 'docker') }}"
                
    Build-and-publish-to-Dockerhub:
        if: | 
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request_target' &&
            github.event.pull_request.merged == 'true' &&
            contains(github.event.pull_request.labels.*.name, 'docker')) ||
            (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: '0'
            - name: Get latest release tag
              id: get_tag
              run: |
                LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
                echo "RELEASE_TAG=${LATEST_TAG}-develop" >> $GITHUB_ENV
                else
                echo "RELEASE_TAG=${LATEST_TAG}" >> $GITHUB_ENV
                fi