name: release 

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: [Semantic Versioning for Patches]
    types:
      - completed

jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history is fetched
          ref: main
        
      - name: Get Latest Tag
        id: get-latest-tag
        if: |
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion  == 'success'
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Release from Workflow Run
        if: |
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion  == 'success'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true 
          append_body: true
          tag_name: ${{ steps.get-latest-tag.outputs.latest_tag }}
          files: |
            src/*
            LICENSE

      - name: Release from Tag Push
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true 
          append_body: true

  write_changelog:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # Ensure all history is fetched
          ref: main
      
      - name: Set Git Author to GitHub Actions Bot
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com""
  
      
      - name: Write CHANGELOG.md      
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
