name: release 

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: [Semantic Versioning for Patches]
    types:
      - completed

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get-latest-tag
        if: github.event_name == 'workflow_run' 
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Release from Workflow Run
        if: github.event_name == 'workflow_run'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true 
          append_body: true
          tag_name: ${{ steps.get-latest-tag.outputs.latest_tag }}

      - name: Release from Tag Push
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true 
          append_body: true

      - name: Write CHANGELOG.md      
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
