name: Ruff
on: 
    push:
        paths:
            - 'src/**'
jobs:
  ruff:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push') }}
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1