name: Semantic Versioning for Tags

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: |
        github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'main' &&
        contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Call Check Changelog Workflow
        id: check-changelog
        uses: ./.github/workflows/check-changelog.yaml

      - name: Bump Version and Tag
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |

          latest_tag="${{ steps.check-changelog.outputs.current_version }}"
          next_version="${{ steps.check-changelog.outputs.next_version }}"

          echo "Bumping version from $latest_tag to v$next_version"

          # Tag the new version
          git tag "v$next_version"

          # Configure GitHub token authentication
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

          # Push the new tag to the remote repository
          git push origin "v$next_version"

      - name: Extract Release Notes
        id: extract_notes
        run: |
          release_notes="${{ steps.check-changelog.outputs.release_notes }}"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$release_notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: "v${{ steps.check-changelog.outputs.next_version }}"
          release_name: Release "v${{ steps.check-changelog.outputs.next_version }}"
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false